### ISSUE TITLE
OpenGraph tags use "property" instead of "name" as attribute.

### ISSUE THREAD

**Issue by christophrumpel** [juampi92/test-seo#1]
Hey,

Thanks for the package. Like it a lot but ran into an issue.

The current implementation only checks the `name` attribute for `twitter()` and `openGraph()` methods. 

It seems this is correct for Twitter (https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started) but it seems the default attribute name is `property` for open graph tags. (https://ogp.me/)

**Comment by juampi92** [comment]
I opened a PR with the fix, in case you wanna take a look: https://github.com/juampi92/test-seo/pull/3
