### ISSUE TITLE
[Feature] What about supporting open graph and twitter tags better

### ISSUE THREAD

**Issue by christophrumpel** [juampi92/test-seo#2]
Hey,

Currently, when I want to test an open graph or Twitter tag, I have to do:

`expect($seo->data)->twitter()->get('image')->toBe('...');`

I know this is a very flexible way to get a tag, but I believe there are a few very important ones for open graph and twitter, that 90% of the users will need to check.

So what about we add support for them directly like this?

![pest_seo](https://user-images.githubusercontent.com/1394539/189095103-167d6a52-941a-449c-9eed-f59ab4ad87c2.png)

For open graph the most important ones are:
* og:type
* og:url
* og:title
* og:descripton
* og:image

For Twitter the most important one is:
* twitter:card

You can define other tags like image, title, etc. for Twitter too, but Twitter falls back to check for open graph tags as well, so actually, you only need the `card` tag for Twitter.

**Comment by juampi92** [comment]
Sounds great! Perhaps a magic getter that is internally doing the `get('image')` will be the simplest.
